project_id = "diiajtshvyqqfgzfzjis"

[functions.execute-code]
verify_jwt = false

[functions.glitchy-hint]
verify_jwt = false

[functions.analyze-code]
verify_jwt = false

[functions.analyze-exam]
verify_jwt = false

[functions.generate-story]
verify_jwt = false

[functions.send-admin-invite]
verify_jwt = false
